### ISSUE TITLE
We need the docs translated into many languages.

### ISSUE THREAD

**Issue by riley** [coralproject/reef#8]
See title. Should we pay a firm as we go along, or just draw on our multi-lingual team until we get some more momentum (and stuff to document)?

I think we have several languages (and character sets!) on our team that we can start with. I don't want to name them for fear of leaving someone out :) Maybe volunteer your linguistic speciality in the comments?

**Comment by gabelula** [comment]
I think we mostly need to have a plan on translation. If we translate documents to other languages, how are we going to maintain them? We can do it and at the same time we need to be careful because it is kind of a lot of work. 

More important than documentation right now is to be sure that we have apps that are internationalized from the beginning.

**Comment by jde** [comment]
Agreed on holding off on explicitly pursuing document translation until a stable state has been reached for major releases.  

Also, +1 for FE translation issues as tracked here: https://github.com/coralproject/cay/issues/9

Closing for now.  Adding to ROADMAP.  Will open an issue referencing the ROADMAP once this is prioritized.
